import './styles.css';
import { createClient } from '@supabase/supabase-js';
import { config,validateConfig } from './config.js';
import { duration,labels,csv,metrics,serialQueue } from './utils.js';
const $=id=>document.getElementById(id), settings=$('settingsForm'),memberForm=$('memberForm');
let db,state=null,session=null,team=null,adminView=false,dirty=false,settingsRevision=null,busy=false,offset=0,failures=0,lastSuccess=0,pollTimer=null,refreshPending=false,authEpoch=0,history=[],audio=null,prior=null,warned=null,newTeam=false,stateVersion=null,probeSupported=true;
const enqueue=serialQueue();
const el=(tag,text='',className='')=>{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;};
function report(text,isError=false){const target=$(isError?'error':'message');target.textContent=text;target.hidden=!text;if(!isError)$('error').hidden=true;}
function describeError(e){if(e?.message?.includes('Invalid login credentials'))return 'Adresse e-mail ou mot de passe incorrect.';if(e?.message?.includes('Failed to fetch')||e?.name==='AbortError')return 'Connexion indisponible. Réessayez dans quelques instants.';return e?.message||String(e);}
function buttons(){document.querySelectorAll('button').forEach(b=>{b.disabled=busy;});$('exportCsv').disabled=busy||!history.length;if(state){const mine=state.myLatest,open=['waiting','offered','active'].includes(mine?.status);$('action').disabled=busy||!lastSuccess||(!open&&!state.open)||Date.now()-lastSuccess>120000;}}
async function run(fn){if(busy)return;busy=true;buttons();report('');try{await fn();}catch(e){report(describeError(e),true);}finally{busy=false;buttons();}}
async function rpc(name,args={}){const epoch=authEpoch;return enqueue(async()=>{if(epoch!==authEpoch)throw Error('Session modifiée. Réessayez.');const {data,error}=await db.rpc(name,args).abortSignal(AbortSignal.timeout(15000));if(error)throw error;if(epoch!==authEpoch)throw Error('Session modifiée. Réessayez.');return data;});}
function apply(data){state=data;stateVersion=null;offset=Date.parse(data.serverNow)-Date.now();lastSuccess=Date.now();failures=0;$('connection').textContent='À jour · '+new Date(lastSuccess).toLocaleTimeString('fr-FR');render();if(data.message)report(data.message);}
async function refresh(force=false){if(!session||refreshPending)return;refreshPending=true;try{let result=null;if(probeSupported){try{result=await rpc('ba_poll',{p_team:team,p_version:force?null:stateVersion});}catch(e){if(e.code==='PGRST202'){probeSupported=false;}else throw e;}}if(!probeSupported){apply(await rpc('ba_state',{p_team:team}));}else if(result.state){apply(result.state);stateVersion=result.version;}else{offset=Date.parse(result.serverNow)-Date.now();lastSuccess=Date.now();failures=0;$('connection').textContent='À jour · '+new Date(lastSuccess).toLocaleTimeString('fr-FR');render();}}catch(e){failures++;if(e.code==='42501'){state=null;stateVersion=null;$('app').hidden=true;$('auth').hidden=false;$('boot').hidden=true;}$('connection').textContent='Connexion interrompue · données anciennes';report(describeError(e),true);}finally{refreshPending=false;schedule();}}
function schedule(){clearTimeout(pollTimer);if(!session)return;const engaged=['waiting','offered','active'].includes(state?.myLatest?.status);const base=document.hidden?60000:engaged||adminView?15000:60000;pollTimer=setTimeout(refresh,Math.min(120000,base*2**Math.min(failures,3)));}
function fmtDate(value){return value?new Date(value).toLocaleString('fr-FR',{timeZone:'Europe/Paris',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';}
function optionList(select,teams,value){const signature=JSON.stringify(teams.map(t=>[t.id,t.name]));if(select.dataset.signature!==signature){select.replaceChildren(...teams.map(t=>{const o=el('option',t.name);o.value=t.id;return o;}));select.dataset.signature=signature;}select.value=value;}
function fillSettings(t){for(const key of ['name','max_breaks','break_minutes','offer_seconds'])settings.elements[key].value=t[key];for(const key of ['opens','closes'])settings.elements[key].value=t[key].slice(0,5);settings.elements.suspended.checked=t.suspended;document.querySelectorAll('#weekdays input').forEach(n=>n.checked=t.weekdays.includes(+n.value));settingsRevision=t.revision;dirty=false;$('dirtyLabel').hidden=true;}
function renderLists(){const signature=JSON.stringify([state.requests,adminView]);if($('breaks').dataset.signature===signature)return;$('breaks').dataset.signature=signature;
 const active=state.requests.filter(r=>r.status==='active'),waiting=state.requests.filter(r=>r.status!=='active');
 for(const [id,items]of[['breaks',active],['queue',waiting]]){const ul=$(id);ul.replaceChildren();if(!items.length)ul.append(el('li',id==='breaks'?'Personne en pause.':'Aucune demande en attente.','empty'));items.forEach((r,i)=>{const li=el('li'),person=el('div','','person');person.append(el('strong',(id==='queue'?`${i+1}. `:'')+r.name+(r.mine?' · vous':'')),el('small',r.status==='active'?'Départ à '+fmtDate(r.startedAt):r.status==='offered'?'Place réservée, confirmation attendue':'Demande à '+fmtDate(r.requestedAt)));const actions=el('div','','row');if(r.status!=='waiting'){const clock=el('span','','clock');clock.dataset.deadline=r.status==='active'?r.dueAt:r.offerExpiresAt;clock.dataset.kind=r.status;actions.append(clock);}if(adminView){const button=el('button',r.status==='active'?'Confirmer le retour':'Retirer','quiet');button.dataset.remove=r.id;actions.append(button);}li.append(person,actions);ul.append(li);});}
}
function render(){if(!state)return;$('app').hidden=false;$('auth').hidden=true;$('boot').hidden=true;$('who').textContent=state.member.display_name;$('identity').hidden=false;$('teamLabel').textContent=state.team.name;$('adminTab').hidden=state.member.role!=='admin';if(state.member.role!=='admin')adminView=false;
 $('personalView').hidden=adminView;$('adminView').hidden=!adminView;$('adminToolbar').hidden=!adminView;$('personalTab').setAttribute('aria-pressed',String(!adminView));$('adminTab').setAttribute('aria-pressed',String(adminView));
 optionList($('teamSelect'),state.teams,state.team.id);const selectedMemberTeam=memberForm.elements.team_id.value;optionList($('memberTeam'),state.teams,selectedMemberTeam||state.team.id);
 if(!dirty&&!newTeam)fillSettings(state.team);
 const count=status=>state.requests.filter(r=>r.status===status).length;
 $('activeCount').textContent=count('active');$('offeredCount').textContent=count('offered');$('waitingCount').textContent=count('waiting');$('freeCount').textContent=Math.max(0,state.team.max_breaks-count('active')-count('offered'));
 const days=['','lun.','mar.','mer.','jeu.','ven.','sam.','dim.'];$('scheduleInfo').textContent=(state.open?'Départs ouverts':'Départs suspendus ou hors horaires')+' · '+state.team.max_breaks+' places · '+state.team.break_minutes+' min · '+state.team.opens.slice(0,5)+'–'+state.team.closes.slice(0,5)+' (Paris) · '+state.team.weekdays.map(x=>days[x]).join(', ');
 renderLists();tick();buttons();schedule();}
function tick(){if(!state)return;const now=Date.now()+offset;document.querySelectorAll('[data-deadline]').forEach(n=>{const left=Date.parse(n.dataset.deadline)-now;n.textContent=left<0?(n.dataset.kind==='active'?'Dépassement +'+duration(left):'Actualisation…'):duration(left);n.classList.toggle('late',left<0);});
 const r=state.myLatest,active=r?.status==='active',offered=r?.status==='offered',waiting=r?.status==='waiting';$('cancel').hidden=!offered;
 $('personalTitle').textContent=active?'Votre pause est en cours':offered?'Une place vous attend':waiting?'Votre demande est dans la file':'Prêt pour une pause ?';
 $('action').textContent=active?'Je suis de retour':offered?'Je pars en pause':waiting?'Annuler ma demande':'Demander une pause';
 const left=active?Date.parse(r.due_at)-now:offered?Date.parse(r.offer_expires_at)-now:null;
 $('timer').textContent=left===null?'':left<0?(active?'+'+duration(left):'0:00'):duration(left);
 $('personalDescription').textContent=active?(left<0?'Durée prévue dépassée. Votre place reste occupée jusqu’à votre retour.':'Votre place sera libérée quand vous confirmerez votre retour.'):offered?'Confirmez votre départ avant la fin du compte à rebours.':waiting?'Position '+(state.requests.filter(x=>x.status!=='active').findIndex(x=>x.mine)+1)+' dans la file. Une alerte vous préviendra.':r?.status==='expired'?'Votre dernière proposition a expiré. Vous pouvez refaire une demande.':state.open?'Une confirmation vous sera demandée lorsqu’une place sera disponible.':'Les départs reprendront selon les règles du pilotage.';
 const key=r?`${r.id}:${r.status}`:'none';if(key!==prior){$('personalAlert').textContent='';if(offered)notify('Une place est disponible : confirmez votre départ.');else if(r?.status==='expired')notify('Votre proposition a expiré. Vous pouvez refaire une demande.');else if(r?.status==='completed'&&prior?.endsWith(':active'))notify('Votre retour a été enregistré.');prior=key;}
 if(active&&left<=120000&&warned!==r.id){warned=r.id;notify(left<=0?'La durée prévue de votre pause est dépassée.':'Il reste moins de deux minutes de pause.');}
 if(Date.now()-lastSuccess>120000)$('connection').textContent='Données anciennes · actualisation nécessaire';buttons();}
function notify(text){$('personalAlert').textContent=text;document.title='🔔 '+text;setTimeout(()=>document.title='Break App · Préproduction',8000);if($('sound').checked&&audio){const oscillator=audio.createOscillator(),gain=audio.createGain();gain.gain.value=.08;oscillator.connect(gain).connect(audio.destination);oscillator.frequency.value=880;oscillator.start();oscillator.stop(audio.currentTime+.3);}try{if(Notification.permission==='granted')new Notification('Break App · Préproduction',{body:text});}catch{} }
$('notifications').onclick=()=>run(async()=>{if(!('Notification'in window)){report('Ce navigateur ne propose pas les notifications. Les alertes visuelles restent actives.');return;}const permission=await Notification.requestPermission();$('notificationStatus').textContent=permission==='granted'?'Notifications autorisées':permission==='denied'?'Notifications bloquées dans le navigateur':'Autorisation non accordée';const Audio=window.AudioContext||window.webkitAudioContext;if(Audio){audio??=new Audio();await audio.resume();}notify('Test des alertes : vous êtes prêt.');});
try{$('sound').checked=localStorage.getItem('break-preprod-sound')==='true';}catch{}
$('sound').onchange=async()=>{try{localStorage.setItem('break-preprod-sound',String($('sound').checked));const Audio=window.AudioContext||window.webkitAudioContext;if($('sound').checked&&Audio){audio??=new Audio();await audio.resume();}}catch{}};
$('action').onclick=()=>run(async()=>{const r=state.myLatest;const action=r?.status==='active'?'return':r?.status==='offered'?'accept':r?.status==='waiting'?'cancel':'request';apply(await rpc('ba_act',{p_action:action,p_request_id:action==='request'?null:r.id}));});
$('cancel').onclick=()=>run(async()=>apply(await rpc('ba_act',{p_action:'cancel',p_request_id:state.myLatest.id})));
$('refresh').onclick=()=>run(refresh);
$('loginForm').onsubmit=e=>{e.preventDefault();run(async()=>{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(error)throw error;await adoptSession(data.session);});};
$('logout').onclick=()=>run(async()=>{const {error}=await db.auth.signOut({scope:'local'});if(error)throw error;await adoptSession(null);});
async function adoptSession(next){if(session?.access_token===next?.access_token&&session!==null)return;session=next;stateVersion=null;probeSupported=true;authEpoch++;clearTimeout(pollTimer);if(!next){state=null;team=null;history=[];dirty=false;newTeam=false;prior=null;warned=null;lastSuccess=0;adminView=false;$('app').hidden=true;$('identity').hidden=true;$('auth').hidden=false;$('boot').hidden=true;$('error').hidden=true;$('message').hidden=true;$('password').value='';return;}$('identity').hidden=false;$('who').textContent=next.user.email;await refresh();}
async function switchView(admin){if(dirty&&!confirm('Abandonner les paramètres non enregistrés ?'))return;dirty=false;newTeam=false;adminView=admin;team=admin?(team||state.member.team_id):null;history=[];await refresh(true);if(admin)await loadMembers();}
$('personalTab').onclick=()=>run(()=>switchView(false));$('adminTab').onclick=()=>run(()=>switchView(true));
$('teamSelect').onchange=()=>run(async()=>{if(dirty&&!confirm('Abandonner les paramètres non enregistrés ?')){$('teamSelect').value=state.team.id;return;}dirty=false;newTeam=false;team=$('teamSelect').value;clearHistory();await refresh(true);});
settings.oninput=()=>{dirty=true;$('dirtyLabel').hidden=false;};
$('discardSettings').onclick=()=>{newTeam=false;fillSettings(state.team);};
$('newTeam').onclick=()=>{if(dirty&&!confirm('Abandonner les paramètres non enregistrés ?'))return;fillSettings({...state.team,name:'Nouvelle équipe'});newTeam=true;dirty=true;$('dirtyLabel').hidden=false;settings.scrollIntoView({behavior:'smooth'});settings.elements.name.focus();};
settings.onsubmit=e=>{e.preventDefault();run(async()=>{const values={};for(const key of ['name','opens','closes'])values[key]=settings.elements[key].value;for(const key of ['max_breaks','break_minutes','offer_seconds'])values[key]=+settings.elements[key].value;values.suspended=settings.elements.suspended.checked;values.weekdays=[...document.querySelectorAll('#weekdays input:checked')].map(n=>+n.value);if(!values.weekdays.length)throw Error('Sélectionnez au moins un jour.');if(values.opens>=values.closes)throw Error('L’heure de fin doit suivre l’heure de début.');const data=await rpc('ba_save_team',{p_team:newTeam?null:state.team.id,p_values:values,p_revision:newTeam?null:settingsRevision});dirty=false;newTeam=false;team=data.team.id;apply(data);});};
async function adminAction(action,id=null){const text=action==='remove'?'Confirmer le retrait ou le retour de cette personne ?':action==='clear_queue'?'Vider toutes les demandes de cette équipe ?':'Clôturer toutes les pauses et demandes de cette équipe ?';if(!confirm(text))return;apply(await rpc('ba_admin_action',{p_action:action,p_team:state.team.id,p_request_id:id}));clearHistory();}
$('clearQueue').onclick=()=>run(()=>adminAction('clear_queue'));$('resetTeam').onclick=()=>run(()=>adminAction('reset'));
document.addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(button)run(()=>adminAction('remove',+button.dataset.remove));});
let members=[];
async function loadMembers(){members=await rpc('ba_members');$('members').replaceChildren(...members.map(m=>{const li=el('li'),info=el('div','','person');info.append(el('strong',m.display_name+(m.enabled?'':' · désactivé')),el('small',m.email+' · '+(m.role==='admin'?'Pilotage':'Conseiller')));const edit=el('button','Modifier','quiet');edit.onclick=()=>{for(const key of ['email','display_name','team_id','role'])memberForm.elements[key].value=m[key];memberForm.elements.enabled.checked=m.enabled;memberForm.elements.email.focus();};li.append(info,edit);return li;}));}
$('loadMembers').onclick=()=>run(loadMembers);
memberForm.onsubmit=e=>{e.preventDefault();run(async()=>{await rpc('ba_save_member',{p_email:memberForm.elements.email.value,p_name:memberForm.elements.display_name.value,p_team:memberForm.elements.team_id.value,p_role:memberForm.elements.role.value,p_enabled:memberForm.elements.enabled.checked});await loadMembers();report('Compte mis à jour.');});};
function clearHistory(){history=[];$('historyRows').replaceChildren();$('historyMetrics').replaceChildren();$('historyInfo').textContent='Chargez l’historique de cette équipe.';$('audit').replaceChildren();buttons();}
$('historyDays').onchange=clearHistory;
$('loadHistory').onclick=()=>run(async()=>{const data=await rpc('ba_history',{p_team:state.team.id,p_days:+$('historyDays').value});history=data.rows;const m=metrics(history);$('historyMetrics').replaceChildren(...[['Demandes',m.requests],['Pauses terminées',m.completed],['Attente moyenne',duration(m.averageWait)],['Dépassements terminés',m.overdue]].map(([label,value])=>{const n=el('div');n.append(el('span',label),el('strong',String(value)));return n;}));$('historyInfo').textContent=`${history.length} ligne(s) chargée(s) sur ${data.total}.`+(data.total>5000?' Résultat partiel : choisissez une période plus courte.':'');$('historyRows').replaceChildren(...history.map(r=>{const tr=el('tr');for(const value of [r.display_name,fmtDate(r.requested_at),fmtDate(r.started_at),fmtDate(r.ended_at),labels[r.status]])tr.append(el('td',value));return tr;}));$('audit').replaceChildren(...data.audit.map(a=>el('li',`${fmtDate(a.occurred_at)} · ${a.actor||'Système'} · ${a.action}`)));});
$('exportCsv').onclick=()=>{const url=URL.createObjectURL(new Blob([csv(history)],{type:'text/csv;charset=utf-8'}));const link=el('a');link.href=url;link.download='break-app-preprod-historique.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();else schedule();});
window.addEventListener('online',()=>refresh());
window.addEventListener('offline',()=>{$('connection').textContent='Hors connexion · données anciennes';});
try{
 validateConfig();
 db=createClient(config.url,config.publishableKey,{auth:{storageKey:'break-app-preprod-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
 db.auth.onAuthStateChange((_event,next)=>{setTimeout(()=>{if(session?.access_token!==next?.access_token)adoptSession(next).catch(e=>report(describeError(e),true));},0);});
 const {data,error}=await db.auth.getSession();if(error)throw error;await adoptSession(data.session);
 setInterval(tick,1000);
}catch(e){$('boot').hidden=true;report(describeError(e),true);}
